
# Set the type to UTF-8 for TextMate bundles
export LC_CTYPE=en_US.UTF-8

# Various developer tools that I usually put on an OS X install
export PATH=/opt/subversion/bin:$PATH
export PATH=/usr/local/git/bin:$PATH
export PATH=/Library/Frameworks/Mono.framework/Versions/Current/bin:$PATH
export PATH=/Developer/usr/bin:/Developer/usr/sbin:$PATH

# Set paths for MacPorts
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export MANPATH=/opt/local/share/man:$MANPATH