" .vimrc
" Heavily based on http://www.jonlee.ca/hacking-vim-the-ultimate-vimrc/
" Ross Nelson <ross.nelson%gmail_com@localhost>

" Install the following:
"   - pathogen: https://github.com/tpope/vim-pathogen#readme
"   - fugitive: https://github.com/tpope/vim-fugitive#readme

" \c: run the current buffer through wc
map <silent> <leader>c :%w !wc<CR>

" \s: run the current file through aspell
map <silent> <leader>s :!aspell check %<CR>

" Enable pathogen
call pathogen#infect()

" Turn on line numbering
set number

" Turn on syntax highlighting
set t_Co=256
colorscheme zenburn
syntax enable

" Code folding
set foldenable
set fdm=indent
nnoremap <space> za

" Turn word wrapping off
set wrap!

" Muck with intdentation
set smartindent
set tabstop=4
set shiftwidth=4
filetype indent on

" Show whitespace characters; toggle with F11
set listchars=eol:$,tab:>-,trail:.,extends:>,precedes:<,nbsp:_
highlight SpecialKey term=standout ctermfg=darkgray guifg=darkgray
noremap <F11> :set list!<CR>

" Highlight the current line (vim >= 7)
set cursorline
