
# Set variables for all of the possible $JAVA_HOME variables
export HARMONY=/opt/java/harmony/harmony-6.0-jdk-991881
export J9=/opt/java/j9/ibm-java-x86_64-60
export RVM=/opt/java/jikes/jikesrvm-3.1.1-development_x86_64-linux
export OJDK6=/usr/lib/jvm/java-6-openjdk
#export OJDK7=/usr/lib/jvm/java-7-openjdk
export HS7=/usr/lib/jvm/java-1.7.0-hotspot
